#spring.datasource.url=jdbc:postgresql://postgres:5432/patientdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.kafka.bootstrap-servers=kafka:9092
#
#spring.data.redis.host=redis
#spring.data.redis.port=6379
#
## gRPC (VERY IMPORTANT)
#grpc.client.billing-service.address=static://billing-service:9001
#spring.jpa.hibernate.ddl-auto=update


spring.application.name=patient-service1
server.port=4000

# PostgreSQL (DOCKER)
spring.datasource.url=jdbc:postgresql://postgres:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# Kafka (DOCKER)
spring.kafka.bootstrap-servers=kafka:9092

# Redis (DOCKER)
spring.data.redis.host=redis
spring.data.redis.port=6379

# gRPC (DOCKER)
grpc.client.billing-service.address=static://billing-service:9001

# JPA (VERY IMPORTANT)
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.root=info