#spring.application.name=patient-service1
#
#server.port=4000
#
## PostgreSQL (Docker)
#spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
#
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#
## Hikari
##spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
## Logging
#logging.level.root=info
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#grpc.client.billing-service.address=billing-service:9001


spring.application.name=patient-service1
server.port=4000

# PostgreSQL (LOCAL)
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka (LOCAL)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis (LOCAL)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# gRPC (LOCAL)
grpc.client.billing-service.address=localhost:9001

# JPA
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.root=info