<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- ✅ STABLE SPRING BOOT VERSION -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>com.pm</groupId>
    <artifactId>billing-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>billing-service</name>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>

        <!-- ✅ Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- ✅ Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- ✅ gRPC -->
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>3.0.0.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.57.2</version>
        </dependency>

        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>1.57.2</version>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.24.4</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
        </dependency>
        <dependency>
            <groupId>com.pm</groupId>
            <artifactId>common-dto</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
        </dependency>

    </dependencies>

    <build>
<!--        <plugins>-->

<!--            &lt;!&ndash; ✅ SPRING BOOT JAR FIX &ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>org.springframework.boot</groupId>-->
<!--                <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--            </plugin>-->

<!--            &lt;!&ndash; ✅ PROTOBUF GENERATION &ndash;&gt;-->
<!--&lt;!&ndash;            <plugin>&ndash;&gt;-->
<!--&lt;!&ndash;                <groupId>com.github.os72</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                <artifactId>protoc-jar-maven-plugin</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                <version>3.11.4</version>&ndash;&gt;-->

<!--&lt;!&ndash;                <executions>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>run</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                        <configuration>&ndash;&gt;-->

<!--&lt;!&ndash;                            <includeStdTypes>true</includeStdTypes>&ndash;&gt;-->

<!--&lt;!&ndash;                            <inputDirectories>&ndash;&gt;-->
<!--&lt;!&ndash;                                <include>src/main/proto</include>&ndash;&gt;-->
<!--&lt;!&ndash;                            </inputDirectories>&ndash;&gt;-->

<!--&lt;!&ndash;                            <outputTargets>&ndash;&gt;-->

<!--&lt;!&ndash;                                <outputTarget>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <type>java</type>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                        target/generated-sources/protobuf/java&ndash;&gt;-->
<!--&lt;!&ndash;                                    </outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                </outputTarget>&ndash;&gt;-->

<!--&lt;!&ndash;                                <outputTarget>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <type>grpc-java</type>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <pluginArtifact>&ndash;&gt;-->
<!--&lt;!&ndash;                                        io.grpc:protoc-gen-grpc-java:1.57.2&ndash;&gt;-->
<!--&lt;!&ndash;                                    </pluginArtifact>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                        target/generated-sources/protobuf/grpc-java&ndash;&gt;-->
<!--&lt;!&ndash;                                    </outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                </outputTarget>&ndash;&gt;-->

<!--&lt;!&ndash;                            </outputTargets>&ndash;&gt;-->

<!--&lt;!&ndash;                        </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                </executions>&ndash;&gt;-->
<!--&lt;!&ndash;            </plugin>&ndash;&gt;-->
<!--&lt;!&ndash;            <plugin>&ndash;&gt;-->
<!--&lt;!&ndash;                <groupId>org.xolstice.maven.plugins</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                <artifactId>protobuf-maven-plugin</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                <version>0.6.1</version>&ndash;&gt;-->
<!--&lt;!&ndash;                <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;                    <protocArtifact>com.google.protobuf:protoc:3.25.3:exe:win-x86_64</protocArtifact>&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;                    <protocArtifact>com.google.protobuf:protoc:3.21.12:exe:win-x86_64</protocArtifact>&ndash;&gt;-->
<!--&lt;!&ndash;                    <pluginId>grpc-java</pluginId>&ndash;&gt;-->
<!--&lt;!&ndash;&lt;!&ndash;                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.61.0:exe:win-x86_64</pluginArtifact>&ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;                    <protocArtifact>com.google.protobuf:protoc:3.21.12:exe:win-x86_64</protocArtifact>&ndash;&gt;-->
<!--&lt;!&ndash;                </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                <executions>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>compile</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>compile-custom</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                </executions>&ndash;&gt;-->
<!--&lt;!&ndash;            </plugin>&ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>org.xolstice.maven.plugins</groupId>-->
<!--                <artifactId>protobuf-maven-plugin</artifactId>-->
<!--                <version>0.6.1</version>-->

<!--                <configuration>-->
<!--                    <protocArtifact>com.google.protobuf:protoc:3.21.12</protocArtifact>-->
<!--                    <pluginId>grpc-java</pluginId>-->
<!--                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.56.1</pluginArtifact>-->
<!--                </configuration>-->

<!--                <executions>-->
<!--                    <execution>-->
<!--                        <goals>-->
<!--                            <goal>compile</goal>-->
<!--                            <goal>compile-custom</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->

<!--        </plugins>-->

            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>

    </build>

</project>